### ISSUE TITLE
做成这种桌面窗口还有桌面歌词是用的什么技术啊，看你包里面没有electron

### ISSUE THREAD

**Issue by dselegent** [Cashew-wood/som_music#2]

**Comment by Cashew-wood** [comment]
我自己封装的webviw2，文件只有2MB



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月09日 14:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Cashew-wood/som_music] 做成这种桌面窗口还有桌面歌词是用的什么技术啊，看你包里面没有electron (Issue #2) |
