### ISSUE TITLE
本地音乐点击播放提示文件已失效

### ISSUE THREAD

**Issue by kirbystudy** [Cashew-wood/som_music#4]
系统：win11
npm -v：9.5.0
node -v：v18.14.2

1. 拖入音乐文件夹没反应
2. 拖入音乐文件.mp3 点击播放提示文件已失效
![image](https://user-images.githubusercontent.com/63231787/223020028-6df17a23-a37e-4c06-8f91-e22d705a4bc7.png)

**Comment by Cashew-wood** [comment]
已修复，拉最新代码试试

**Comment by kirbystudy** [comment]
拖入音乐文件可以，但是拖入文件夹还是没反应。

**Comment by Cashew-wood** [comment]
刚修复了，拉最新代码试试

**Comment by kirbystudy** [comment]
拖入文件夹没问题了，但是所有的文件都显示出来了。这里可以优化以下，只显示mp3,flac... 这些后缀名的文件。

**Comment by Cashew-wood** [comment]
![009DA963](https://user-images.githubusercontent.com/84235524/223052545-06633be3-ca9f-4a62-ba6a-29cc65372c60.gif)
